### ISSUE TITLE
Development environment issues

### ISSUE THREAD

**Issue by henrikjohansson712** [devture/matrix-corporal#18]
I tried spinning up your dev environment using the [instructions](https://github.com/devture/matrix-corporal/blob/master/docs/development.md) and ran in to a couple of problems.

The first problem was that the postgres container crashed on start up because it couldn't access the necessary files as it didn't have root access. I fixed this by removing the line `user: ${CURRENT_USER_UID}:${CURRENT_USER_GID}` for postgres in [docker-compose.yaml](https://github.com/devture/matrix-corporal/blob/master/etc/services/docker-compose.yaml) and managed to get everything up and running.

I then followed the instructions to create a user and start the matrix-corporal container, which is where I ran into another problem: When I went to log in to Element, it gave me an error saying the Homeserver URL wasn't pointing to a valid Homeserver, so logging in wasn't possible. Not really sure what to do about this. Is there something that I've missed?

**Comment by spantaleev** [comment]
I just started from scratch (fresh clone and doing the steps specified in `development.md`) and it worked without a hitch.

I'm on Docker 20.10.6 with docker-compose 1.29.1, running `docker-compose` with a regular user.

If you ran some of the steps as `root`, then that might have interfered with things (`CURRENT_USER_UID` and `CURRENT_USER_GID` would be `0`), which likely causes issues. We may modify the `Makefile` to error out with a friendlier message in such cases.

**Comment by henrikjohansson712** [comment]
I'm on Docker 20.10.5 with docker-compose 1.29.0. Not running anything as root, and my user id is forwarded into the container, I can see it in the logs before the container crashes. If it works for you, then I think we can ignore it, because I can work around it.

Do you have any suggestion on how to solve the second part of my problem?

**Comment by spantaleev** [comment]
Oh, right! There was indeed a problem!

The sample configuration in `config.json.dist` was using `127.0.0.1` instead of `0.0.0.0` for `HttpGateway` and `HttpApi`, which meant that container ports weren't exposed properly. It's fixed now. Please rebuild your `config.json` in accordance with the updates you see in daf2d56.

**Comment by henrikjohansson712** [comment]
Working fine now, thanks for helping out!
