### ISSUE TITLE
Unfriendly license

### ISSUE THREAD

**Issue by benlangfeld** [devture/matrix-corporal#20]
The license this project uses makes it unusable for corporate internal deployments. Would you be willing to relicense as GPLv3 or even better Apache v2?

**Comment by benlangfeld** [comment]
@rettichschnidi and @dali99 Could you possibly expand on your downvotes? Why would this be a bad thing?

**Comment by dali99** [comment]
1. AGPL is a perfectly fine license and does not in any way inhibit the use of it for corporate deployments, your policies make it impossible for corporate deployments, not the license. [Do not fall for the Google AGPL FUD](https://drewdevault.com/2020/07/27/Anti-AGPL-propaganda.html).
2. [Internal deployment, wouldn't count as distribution anyways](https://www.gnu.org/licenses/gpl-faq.en.html#InternalDistribution) (I Am not a Lawyer, this is just my understanding of it)
2. It's unlikely a developer has "accidentally" picked the AGPL.
3. The only reason you would want a permissive license (which includes the GPL when you're dealing with 100% server side software) is if you don't want to contribute improvements to the program. Which isnt a benefit to the FOSS community. 

I am personally quite fond of the AGPL and I become a little happy when I see projects in the wild using it.

**Comment by benlangfeld** [comment]
Thank you @dali99 , it does indeed seem we had made an errant interpretation of the extension of the definition of derivative work. After further study, we believe that you are correct that our use case is not impeded by the AGPL. We do, of course, contribute as fully as we possibly can with the OSS community; I myself have released approximately 50% of the code I've written during my entire career as OSS, and avoiding such contribution was far from the intent of my request.
