### ISSUE TITLE
Reconciliation failed

### ISSUE THREAD

**Issue by candyman2903** [devture/matrix-corporal#24]
Hello,

I can't get the Matrix Corporal to work. When I try to start it I get the following error message:

`WARN[0000] Reconciliation failed: Failure determining current state: Post "http://localhost:8008/_matrix/client/r0/login": dial tcp 127.0.0.1:8008: connect: connection refused`

Does anyone have an idea?

I'm using Matrix: 1.78.0

And does Matrix also have to run in Docker or does it not matter?

**Comment by spantaleev** [comment]
You don't need to run Synapse in a container or on the same machine even.

You do need to point matrix-corporal to your homeserver correctly though. Sounds like you've pointed it to `http://localhost:8008` and that there's no homeserver there, so.. adjust your configuration accordingly.

**Comment by candyman2903** [comment]
Same error:

`WARN[0000] Reconciliation failed: Failure determining current state: Post "http://matrix.sershop-int.de:8008/_matrix/client/r0/login": dial tcp 81.169.213.43:8008: connect: connection refused`

**Comment by spantaleev** [comment]
Why are you using `http` and not `https`.. and why do you insist on port `8008` and not `443` (that is.. leaving the port out, if you've prefixed with `https://`).

Try `https://matrix.sershop-int.de`

**Comment by candyman2903** [comment]
Thank you very much. now I get this error:

WARN[0091] Reconciliation failed: Failure determining current state: contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 70 79 82 66 73 68 68 69 78 34 44 34 101 114 114 134 753 110 118 97 108 105 100 32 117 115 101 114 110 97 109 101 32 111 114 32 112 97 115 115 119 111 114 100 34 125] msg=Failed to POST JSON/client coder=0/3 login wrapped to /40/3 client. coder wrapped to /_matrix= M_FORBIDDEN: Invalid username or password

Because it says so in the config.json.dist. Thought it must be like this.
