### ISSUE TITLE
Failed to POST JSON to /_matrix/client/r0/login code=403 wrapped=M_FORBIDDEN: Invalid password

### ISSUE THREAD

**Issue by verymilan** [devture/matrix-corporal#9]
Hi there, i can't bring the Reconciliation to work, as it keeps throwing and Invalid password error.
I have followed the instructions and/but built corporal by hand on the latest release branch.

The error in synapse and corporal suggests that it uses a wrong password, but corporal does not have a password field for the Reconciliation-user and after trying multiple users with admin permissions and double-triple-checking my setup, i am kinda out of ideas right now. :(

**Comment by KB1RD** [comment]
@verymilan You may be looking for https://github.com/devture/matrix-synapse-shared-secret-auth

Once it's set up, you can use [`AuthSharedSecret`](https://github.com/devture/matrix-corporal/blob/master/docs/configuration.md) to set the auth secret to use.

Also, you may be able to get additional help in [#matrix-corporal:devture.com](https://matrix.to/#/!ZAXhfRqRdNttyzGLBL:devture.com?via=devture.com&via=matrix.org&via=tchncs.de)

**Comment by verymilan** [comment]
Thank you, totally forgot about this one: 
I have also asked on matrix a while ago and we figured that i had a duplicate entry in the config, hidden between comments, that made synapse not add the auth provider and caused the issue to happen. :)
